### ISSUE TITLE
App build failed

### ISSUE THREAD

**Issue by marmarquez** [vtex-apps/mega-menu#14]
Hola! 

Me da el siguiente error luego de instalar la app e intentar hacer el link para probar: 

**_App build failed with message: Error with dependency vtex.mega-menu@2.x: App cannot contain billing options: vtex.mega-menu@2.x_**
Alguien tiene idea de lo que puede estar ocurriendo y cómo solucionarlo?

**Comment by mihaidanieldumitru** [comment]
Hy @marmarquez! Put the app in `"peerDependencies"`

**Comment by marmarquez** [comment]
@mihaidanieldumitru thanks! with that it worked!

But now it doesn't show the menu.

I created a menu in the admin, and placed it in this block...

`  // menu
  "flex-layout.row#2-desktop": {
    "props": {
      "horizontalAlign":"center",
      "preventHorizontalStretch": true,
      "verticalAlign": "middle",
      "blockClass": "layoutMenu"
    },
    "children": ["mega-menu"]      // menu -> menu.jsonc
  },
`
but it is not displayed. Do you have any idea why it could be?

**Comment by mihaidanieldumitru** [comment]
@marmarquez You also need to place this block `"mega-menu-trigger-btn"` in the menu-bar where you want the hamburger menu icon to appear

The blocks you placed are for rendering the mega-menu when you click on the trigger button

**Comment by marmarquez** [comment]
thanks! work it!
