### ISSUE TITLE
Mobile version. It is not posible to return to the previous level

### ISSUE THREAD

**Issue by IvanLopezLuna** [vtex-apps/mega-menu#2]
**Describe the bug**
When the user selects a first level option that has a submenu, the second level is displayed but there is no way to go back to the first level options.

**To Reproduce**

1. On a mobile screen resolution, go to [featurenavmegamenu workspace](https://featurenavmegamenu--martimxlite.myvtex.com)
2. Click on the Hamburguer menu
3. Click on the **Deportes** option
4. Try to go back to the first level options to select the option **Marcas**

**Expected behavior**
It is necessary to have a button to return to the previous level.

**Screenshots**
If applicable, add screenshots to help explain your proble
![Screenshot_20211110-143221](https://user-images.githubusercontent.com/23274114/141189096-f5fbab59-84d8-411b-b685-44f9193781aa.jpg)
m
![Screenshot_20211110-143229](https://user-images.githubusercontent.com/23274114/141189103-bcf8b0b1-65ed-4c43-b716-a8b286e53f24.jpg)
.

**Comment by ejisselgb** [comment]
Hello @IvanLopezLuna in the new version, do you have the same problem?

**Comment by IvanLopezLuna** [comment]
Hi @ejisselgb!
The problem was resolved.

Thanks!
